### ISSUE TITLE
Using VNC Viewer with Nodes

### ISSUE THREAD

**Issue by seangerhardt-wf** [elgalu/docker-selenium#132]
#### Operating System
- OS: Mac OS X 10.10.5
#### Image version
- latest elgalu/selenium
#### Docker version
- Docker 1.12.1
#### Docker-Compose
- docker-compose version 1.8.0

Hello,

I'm able to successfully use a VNC viewer when I use a standalone image. Here's a snippet from the docker-compose:
```
  selenium_chrome_standalone:
    volumes:
      - shared:/shared
      - shared:/videos
    image: elgalu/selenium
    shm_size: 4g
    mem_limit: 8g
    memswap_limit: 16g
    environment:
      - VNC_PASSWORD=secret
      - PICK_ALL_RANDMON_PORTS=false
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - VIDEO=true
      - FFMPEG_FRAME_RATE=25
      - VIDEO_FILE_NAME=test_run
      - VIDEO_FILE_EXTENSION=mkv
      - VIDEO_CHUNK_SECS=00:15:00
#    Used for VNC debugging
    ports:
      - "5900:25900"
```

I can then VNC to the image with `open vnc://:secret@192.168.99.100:5900`

Now I want to use a grid with a couple nodes, and still be able to VNC to the nodes running the tests.
**The problem I have is knowing what port to use for VNC**. Using the example docker-compose from this project, that could be any port of 50. I've tried hardcoding the VNC_PORT env vars as well, but have not had any luck. Does anyone know how to use VNC viewer with a node for this project?
```
  selenium_chrome_standalone_hub:
    volumes:
      - shared:/shared
      - shared:/videos
    image: elgalu/selenium
    shm_size: 4g
    mem_limit: 8g
    memswap_limit: 16g
    environment:
      - VNC_PASSWORD=secret
      - GRID=true
      - PICK_ALL_RANDMON_PORTS=false
      - SELENIUM_HUB_PORT=4444
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - CHROME=false
      - FIREFOX=false
      - RC_CHROME=false
      - RC_FIREFOX=false
    ports:
      - "4444:4444"
      - "5900:25900"
      - "40650-40701:40650-40701"

  chrome_node_1:
    volumes:
      - shared:/shared
      - shared:/videos
    image: elgalu/selenium
    network_mode: "service:selenium_chrome_standalone_hub"
    shm_size: 4g
    mem_limit: 8g
    memswap_limit: 16g
      - VNC_PASSWORD=secret
      - SELENIUM_HUB_PORT=4444
      - VNC_FROM_PORT
      - VNC_TO_PORT
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - PICK_ALL_RANDMON_PORTS=true
      - GRID=false
      - CHROME=true
      - FIREFOX=false
      - RC_CHROME=false
      - RC_FIREFOX=false
      - VIDEO=true
      - FFMPEG_FRAME_RATE=25
      - VIDEO_FILE_NAME=test_run
      - VIDEO_FILE_EXTENSION=mkv
      - VIDEO_CHUNK_SECS=00:15:00

  chrome_node_2:
    volumes:
      - shared:/shared
      - shared:/videos
    image: elgalu/selenium
    network_mode: "service:selenium_chrome_standalone_hub"
    shm_size: 4g
    mem_limit: 8g
    memswap_limit: 16g
    environment:
      - DEFAULT_VNC_PORT=40651
      - VNC_PORT=40651
      - VNC_PASSWORD=secret
      - SELENIUM_HUB_PORT=4444
      - VNC_FROM_PORT
      - VNC_TO_PORT
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - PICK_ALL_RANDMON_PORTS=true
      - GRID=false
      - CHROME=true
      - FIREFOX=false
      - RC_CHROME=false
      - RC_FIREFOX=false
      - VIDEO=true
      - FFMPEG_FRAME_RATE=25
      - VIDEO_FILE_NAME=test_run
      - VIDEO_FILE_EXTENSION=mkv
      - VIDEO_CHUNK_SECS=00:15:00
```

**Comment by elgalu** [comment]
You setup looks quite good!

I suggest this changes and try again:

1. Remove `DEFAULT_VNC_PORT`, `VNC_FROM_PORT` and `VNC_TO_PORT` from everywhere.

2. Replace `"40650-40701:40650-40701"` with `"40650-40651:40650-40651"`
within `ports` => `selenium_chrome_standalone_hub` as you only need 2.

3. Remove `- "5900:25900"` as you will be using 40650 and 40651 instead and is already covered in the range so just remove this to avoid confusion.

4. Add `- VNC_PORT=40650` in `chrome_node_1` as you did similarly for the second node.

You should then be able to vnc into both separately:
- `vnc://:secret@192.168.99.100:40650`
- `vnc://:secret@192.168.99.100:40651`

Optional:

4. Remove `VNC_PASSWORD=secret` and `secret` from everywhere, it seems you don't really need a password. The default now is no password so it will connect directly.

**Comment by seangerhardt-wf** [comment]
Leo, thanks for the quick feedback.
 
I've tested again with the above suggestions, and I can successfully view the node using port 40650, which is great news!

I am unable to view the second node using port 40651, and a `docker stats` command implies that while it's up, it may not be receiving tests as it's cpu usage is much lower than node 1.

**Comment by elgalu** [comment]
I see, can you paste the new updated docker-compose.yaml? I'll try to see what I missed

**Comment by seangerhardt-wf** [comment]
```
  selenium_chrome_standalone_hub:
    volumes:
      - shared:/shared
      - shared:/videos
    image: elgalu/selenium
    shm_size: 4g
    mem_limit: 8g
    memswap_limit: 16g
    environment:
      - GRID=true
      - PICK_ALL_RANDMON_PORTS=false
      - SELENIUM_HUB_PORT=4444
      - HUB_PORT_4444_TCP_ADDR=selenium_chrome_standalone_hub
      - HUB_PORT_4444_TCP_PORT=4444
      - CHROME=false
      - FIREFOX=false
      - RC_CHROME=false
      - RC_FIREFOX=false
    ports:
      - "4444:4444"
      - "40650-40651:40650-40651"

  chrome_node_1:
    volumes:
      - shared:/shared
      - shared:/videos
    image: elgalu/selenium
    network_mode: "service:selenium_chrome_standalone_hub"
    shm_size: 4g
    mem_limit: 8g
    memswap_limit: 16g
    environment:
      - VNC_PASSWORD=secret
      - VNC_PORT=40650
      - SELENIUM_HUB_PORT=4444
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - PICK_ALL_RANDMON_PORTS=true
      - GRID=false
      - CHROME=true
      - FIREFOX=false
      - RC_CHROME=false
      - RC_FIREFOX=false
      - VIDEO=true
      - FFMPEG_FRAME_RATE=25
      - VIDEO_FILE_NAME=test_run
      - VIDEO_FILE_EXTENSION=mkv
      - VIDEO_CHUNK_SECS=00:15:00

  chrome_node_2:
    volumes:
      - shared:/shared
      - shared:/videos
    image: elgalu/selenium
    network_mode: "service:selenium_chrome_standalone_hub"
    shm_size: 4g
    mem_limit: 8g
    memswap_limit: 16g
    environment:
      - VNC_PASSWORD=secret
      - VNC_PORT=40650
      - SELENIUM_HUB_PORT=4444
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - PICK_ALL_RANDMON_PORTS=true
      - GRID=false
      - CHROME=true
      - FIREFOX=false
      - RC_CHROME=false
      - RC_FIREFOX=false
      - VIDEO=true
      - FFMPEG_FRAME_RATE=25
      - VIDEO_FILE_NAME=test_run
      - VIDEO_FILE_EXTENSION=mkv
      - VIDEO_CHUNK_SECS=00:15:00
```
