### ISSUE TITLE
How do I get the VNC running

### ISSUE THREAD

**Issue by WillGibson** [elgalu/docker-selenium#164]
Hi @elgalu,

This is great tool, thanks for making it.

I've got it working with one of our projects very quickly, but I've no idea how to get at the VNC stuff, which is crucial to us as we're wasting loads of time "working blind".

Our docker-compose-selenium.yml is below.

Have I done something wrong? Or can you give me some pointers as to what I should expect to do to view the tests running via VNC?

```
version: '2.1'

services:
  hub:
    image: elgalu/selenium
    depends_on:
      - nginx
    links:
      - nginx:redacted1.dev
      - nginx:redacted2.dev
    ports:
      - 4444:4444
      - 5900:25900
      - 6080:26080
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - PICK_ALL_RANDOM_PORTS=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - GRID=true
      - CHROME=false
      - FIREFOX=false
      - MOCK_SERVER_HOST=nginx
      - TZ=Europe/London

  chrome:
    image: elgalu/selenium
    depends_on:
      - hub
    links:
      - nginx:redacted1.dev
      - nginx:redacted2.dev
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - PICK_ALL_RANDOM_PORTS=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - VIDEO=${VIDEO-false}
      - GRID=false
      - CHROME=true
      - FIREFOX=false
```

#### Operating System
Linux will-Inspiron-3847 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#### Image version
I have latest version of this image.

#### Docker version
Docker version 17.03.1-ce, build c6d412e

#### Docker-Compose
docker-compose version 1.11.2, build dfed245

**Comment by elgalu** [comment]
expose these on chrome:

```
    ports:
      - 4444:4444
      - 5900:25900
      - 6080:26080
```

You may find Zalenium live preview a better fit:
https://github.com/zalando/zalenium

**Comment by WillGibson** [comment]
Thanks @elgalu,

So now I have...

```
version: '2.1'

services:
  hub:
    image: elgalu/selenium
    depends_on:
      - nginx
    links:
      - nginx:redacted1.dev
      - nginx:redacted2.dev
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - PICK_ALL_RANDOM_PORTS=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - GRID=true
      - CHROME=false
      - FIREFOX=false
      - MOCK_SERVER_HOST=nginx
      - TZ=Europe/London

  chrome:
    image: elgalu/selenium
    depends_on:
       - hub
    links:
      - nginx:redacted1.dev
      - nginx:redacted2.dev
    ports:
      - 4444:4444
      - 5900:25900
      - 6080:26080
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - PICK_ALL_RANDOM_PORTS=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - VIDEO=${VIDEO-false}
      - GRID=false
      - CHROME=true
      - FIREFOX=false
```

...and these containers...

```
    Name                  Command              State                                     Ports                                   
--------------------------------------------------------------------------------------------------------------------------------
redacted_service2_1      docker-php-entrypoint php-fpm   Up       9000/tcp                                                                 
redacted_chrome_1   entry.sh                        Up       0.0.0.0:5900->25900/tcp, 0.0.0.0:6080->26080/tcp, 0.0.0.0:4444->4444/tcp 
redacted_hub_1      entry.sh                        Up                                                                                
redacted_mysql_1    docker-entrypoint.sh mysqld     Up       0.0.0.0:32830->3306/tcp                                                  
redacted_nginx_1    nginx -g daemon off;            Up       0.0.0.0:32832->443/tcp, 0.0.0.0:32831->80/tcp                            
redacted_node_1     node                            Exit 0                                                                            
redacted_service1_1      docker-php-entrypoint php-fpm   Up       9000/tcp 
```

Behat still works, but still no joy on the VNC front.

I try connecting with Remmina 1.2.0-rcgit-18 (git rcgit-18) and these settings at 0.0.0.0:5900 with no user or pass and it just says VNS server closed the connection.

I've also tried hitting http://0.0.0.0:6080 in my browser, not sure if that's right, but it doesn't work either.

I'll have a look at Zalenium too in case that hits the spot for us.

**Comment by elgalu** [comment]
Now you moved 

```
- 4444:4444
```

To chrome but that belongs to the hub

Sorry I really don't have time to go through your network settings, try opening a question in stackoverflow or switching to Zalenium.

Will close this issue as is not an issue nor a feature request.

**Comment by diemol** [comment]
Hi @WillGibson,

I played for some minutes with that compose file, I removed the nginx stuff (you should be able to add it later), so this worked for me:

```
version: '2.1'

services:
  hub:
    image: elgalu/selenium
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - GRID=true
      - CHROME=false
      - FIREFOX=false
      - MOCK_SERVER_HOST=nginx
      - TZ=Europe/London

  chrome:
    image: elgalu/selenium
    depends_on:
       - hub
    ports:
      - 5900:25900
      - 6080:26080
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - NOVNC=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - VIDEO=${VIDEO-false}
      - GRID=false
      - CHROME=true
      - FIREFOX=false
```
Try http://0.0.0.0:6080 afterwards, and you will see inside the Chrome container. Keep in mind that if you add more containers, you need to map different ports.

The difference is that I removed `PICK_ALL_RANDOM_PORTS=true`. This makes that the ports used to expose the VNC and other services get randomly picked, and this has more priority than the ones you map. 

And, if you have some time, check Zalenium. Most probably you will avoid all this setup hassle.
