### ISSUE TITLE
Can't connect with `vncviewer 0.0.0.0:5900`

### ISSUE THREAD

**Issue by BjornMelgaard** [elgalu/docker-selenium#192]
I've just probably omitted something or misunderstood

I have the following `docker-compose.yml`
```yml
version: '3'

services:
  hub:
    image: elgalu/selenium
    ports:
      # Note 24444 is the default SELENIUM_HUB_PORT inside the container
      #  and  4444 will be mapped into your host for easy access.
      # - 4444:4444
      # We need a fixed port range to expose VNC
      # due to a bug in Docker for Mac beta (1.12)
      # https://forums.docker.com/t/docker-for-mac-beta-not-forwarding-ports/8658/6
      - ${VNC_FROM_PORT-40650}-${VNC_TO_PORT-40700}:${VNC_FROM_PORT-40650}-${VNC_TO_PORT-40700}
      # e.g. (hard-coded)
      # - 40650-40700:40650-40700
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - GRID=true
      - CHROME=false
      - FIREFOX=false

  chrome:
    image: elgalu/selenium
    depends_on:
      - hub
    ports:
      # VNC: See what's going on by connecting your VNC client to 0.0.0.0:5900
      - 5900:40652
      # noVNC: See what's going on by hitting http://0.0.0.0:6080 in your browser
      - 6080:26080
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - NOVNC=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - VNC_FROM_PORT=${VNC_FROM_PORT-40650}
      - VNC_TO_PORT=${VNC_TO_PORT-40700}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - VIDEO=${VIDEO-false}
      - GRID=false
      - CHROME=true
      - FIREFOX=false
```

And I starting it with 
```sh
 ~/work   master ●✚  docker-compose up
Pulling hub (elgalu/selenium:latest)...
latest: Pulling from elgalu/selenium
660c48dd555d: Pulling fs layer
4c7380416e78: Pulling fs layer
......
08c486b3998a: Pull complete
Digest: sha256:114d5db410dd3dec6379bc513aa43a554c637b67e9596c7e023389013061dc2b
Status: Downloaded newer image for elgalu/selenium:latest
Creating work_hub_1 ...
Creating work_hub_1 ... done
Creating work_chrome_1 ...
Creating work_chrome_1 ... done
Attaching to work_hub_1, work_chrome_1
hub_1     | --LOG 22:22:12:215137993 Stopping supervisord to support docker restart...
chrome_1  | --LOG 22:22:12:725309345 Stopping supervisord to support docker restart...
hub_1     | -- INFO: Docker Img. Version: 3.7.1-206
hub_1     | -- INFO: Chrome..... Version: 62.0.3202.94
hub_1     | -- INFO: Firefox.... Version: 57.0
hub_1     | -- INFO: Using Selenium.....:
hub_1     | ***************** BEGIN: Data Processing Agreement *****************
hub_1     | By using this software you agree that the following non-PII
hub_1     | (non personally identifiable information) data will be collected,
hub_1     | processed and used by Docker-selenium for the purpose of improving
hub_1     | our test infrastructure tools. Anonymisation with respect of the IP
hub_1     | address means that only the first two octets of the IP address are
hub_1     | collected. See the complete license at:
hub_1     | https://github.com/elgalu/docker-selenium/blob/master/LICENSE.md
hub_1     | ****************** END: Data Processing Agreement ******************
chrome_1  | -- INFO: Docker Img. Version: 3.7.1-206
chrome_1  | -- INFO: Chrome..... Version: 62.0.3202.94
chrome_1  | -- INFO: Firefox.... Version: 57.0
chrome_1  | -- INFO: Using Selenium.....:
hub_1     | supervisord --version=4.0.0.dev0
chrome_1  | ***************** BEGIN: Data Processing Agreement *****************
chrome_1  | By using this software you agree that the following non-PII
chrome_1  | (non personally identifiable information) data will be collected,
chrome_1  | processed and used by Docker-selenium for the purpose of improving
chrome_1  | our test infrastructure tools. Anonymisation with respect of the IP
chrome_1  | address means that only the first two octets of the IP address are
chrome_1  | collected. See the complete license at:
chrome_1  | https://github.com/elgalu/docker-selenium/blob/master/LICENSE.md
chrome_1  | ****************** END: Data Processing Agreement ******************
hub_1     | 2017-11-21 22:22:14,028 INFO Included extra file "/etc/supervisor/conf.d/novnc.conf" during parsing
hub_1     | 2017-11-21 22:22:14,028 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
hub_1     | 2017-11-21 22:22:14,028 INFO Included extra file "/etc/supervisor/conf.d/selenium-multinode.conf" during parsing
hub_1     | 2017-11-21 22:22:14,029 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-chrome.conf" during parsing
hub_1     | 2017-11-21 22:22:14,030 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-firefox.conf" during parsing
hub_1     | 2017-11-21 22:22:14,030 INFO Included extra file "/etc/supervisor/conf.d/video-rec.conf" during parsing
hub_1     | 2017-11-21 22:22:14,031 INFO Included extra file "/etc/supervisor/conf.d/vnc.conf" during parsing
hub_1     | 2017-11-21 22:22:14,031 INFO Included extra file "/etc/supervisor/conf.d/xmanager.conf" during parsing
hub_1     | 2017-11-21 22:22:14,031 INFO Included extra file "/etc/supervisor/conf.d/xterm.conf" during parsing
hub_1     | 2017-11-21 22:22:14,049 INFO RPC interface 'supervisor' initialized
hub_1     | 2017-11-21 22:22:14,050 INFO RPC interface 'supervisor' initialized
hub_1     | 2017-11-21 22:22:14,051 INFO supervisord started with pid 155
chrome_1  | supervisord --version=4.0.0.dev0
chrome_1  | 2017-11-21 22:22:14,543 INFO Included extra file "/etc/supervisor/conf.d/novnc.conf" during parsing
chrome_1  | 2017-11-21 22:22:14,543 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
chrome_1  | 2017-11-21 22:22:14,543 INFO Included extra file "/etc/supervisor/conf.d/selenium-multinode.conf" during parsing
chrome_1  | 2017-11-21 22:22:14,543 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-chrome.conf" during parsing
chrome_1  | 2017-11-21 22:22:14,543 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-firefox.conf" during parsing
chrome_1  | 2017-11-21 22:22:14,544 INFO Included extra file "/etc/supervisor/conf.d/video-rec.conf" during parsing
chrome_1  | 2017-11-21 22:22:14,544 INFO Included extra file "/etc/supervisor/conf.d/vnc.conf" during parsing
chrome_1  | 2017-11-21 22:22:14,544 INFO Included extra file "/etc/supervisor/conf.d/xmanager.conf" during parsing
chrome_1  | 2017-11-21 22:22:14,544 INFO Included extra file "/etc/supervisor/conf.d/xterm.conf" during parsing
chrome_1  | 2017-11-21 22:22:14,554 INFO RPC interface 'supervisor' initialized
chrome_1  | 2017-11-21 22:22:14,554 INFO RPC interface 'supervisor' initialized
chrome_1  | 2017-11-21 22:22:14,554 INFO supervisord started with pid 155
hub_1     | 2017-11-21 22:22:15,055 INFO spawned: 'xmanager' with pid 158
hub_1     | 2017-11-21 22:22:15,057 INFO spawned: 'vnc' with pid 159
hub_1     | 2017-11-21 22:22:15,060 INFO spawned: 'selenium-hub' with pid 160
hub_1     | 2017-11-21 22:22:15,062 INFO spawned: 'xterm' with pid 161
hub_1     | 2017-11-21 22:22:15,071 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
hub_1     | 2017-11-21 22:22:15,072 INFO success: xterm entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1  | 2017-11-21 22:22:15,557 INFO spawned: 'xmanager' with pid 158
chrome_1  | 2017-11-21 22:22:15,560 INFO spawned: 'vnc' with pid 159
chrome_1  | 2017-11-21 22:22:15,563 INFO spawned: 'novnc' with pid 160
chrome_1  | 2017-11-21 22:22:15,566 INFO spawned: 'selenium-node-chrome' with pid 161
chrome_1  | 2017-11-21 22:22:15,569 INFO spawned: 'xterm' with pid 162
chrome_1  | 2017-11-21 22:22:15,607 INFO success: xterm entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
hub_1     | 2017-11-21 22:22:17,066 INFO success: xmanager entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
hub_1     | 2017-11-21 22:22:17,068 INFO success: vnc entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
chrome_1  | 2017-11-21 22:22:17,571 INFO success: xmanager entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
chrome_1  | 2017-11-21 22:22:17,572 INFO success: vnc entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
chrome_1  | 2017-11-21 22:22:17,573 INFO success: novnc entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
chrome_1  | 2017-11-21 22:22:18,704 INFO success: selenium-node-chrome entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
```

After this I can't connect to `0.0.0.0:5900`, but can connect to `localhost:6080` in browser (`vncviewer 0.0.0.0:5900` worked fine with `SeleniumHQ/docker-selenium`)
```sh
 ~/work   master ●✚  vncviewer 0.0.0.0:5900

TigerVNC Viewer 64-bit v1.7.90
Built on: 2017-11-06 06:57
Copyright (C) 1999-2017 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

Tue Nov 21 23:11:03 2017
 DecodeManager: Detected 4 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       connected to host 0.0.0.0 port 5900
 CConn:       End of stream
```

Logs

```sh
 ~/work   master ●✚  dbash grid_chrome_1
seluser@843ecaa893b3:~$ sudo cat /var/log/cont/vnc-stderr.log
seluser@843ecaa893b3:~$ sudo cat /var/log/cont/vnc-stdout.log
Waiting for X Manager 'fluxbox' to be ready...
Done wait-xmanager.sh
--LOG 22:01:17:919275894 Waiting for VNC to be ready via process, nc or netstat on VNC_PORT=40652...
--LOG 22:01:17:934681551 By_process?
--LOG 22:01:17:957134077 By_process:OK
--LOG 22:01:17:982706681 By_nc?
...........--LOG 22:01:19:388394357 By_nc:OK
--LOG 22:01:19:415412989 By_log_stderr?
21/11/2017 22:01:19 Got connection from client 127.0.0.1
21/11/2017 22:01:19 Got connection from client 127.0.0.1
--LOG 22:01:19:453743572 By_log_stderr:OK
--LOG 22:01:19:464099262 By_log_stdout?
PORT=40652
--LOG 22:01:19:473130237 By_log_stdout:OK
--LOG 22:01:19:508953418 Done wait-vnc.sh
```

Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [x] `Linux machine 4.9.63 #1-NixOS SMP Sat Nov 18 10:22:25 UTC 2017 x86_64 GNU/Linux`

#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

#### Docker version
- [x] I have latest version of docker and I will specify here the output of `docker --version`

Docker version 17.09.0-ce, build afdb6d44a80f777069885a9ee0e0f86cf841b1bb

#### Docker-Compose
_(if using docker-compose)_

- [x] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

docker-compose version 1.15.0, build e12f3b9
