### ISSUE TITLE
Selenium with custom capabilities stopped working after recent update

### ISSUE THREAD

**Issue by BjornMelgaard** [elgalu/docker-selenium#201]
After update from `3.7.1-p7` (latest working version) to `3.8.1-p0` (on this version and never - issue) chrome started ignoring selenium capabilities at all. For example it ignores ` --start-maximized` arg, but when I open chrome inside container from shell with this arg - it works

```
  hub:
    image: elgalu/selenium:3.7.1-p7
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - GRID=true
      - CHROME=false
      - FIREFOX=false

  chrome:
    image: elgalu/selenium:3.7.1-p7
    ports:
      # VNC: See what's going on by connecting your VNC client to 0.0.0.0:5900
      - 5900:25900
      # noVNC: See what's going on by hitting http://0.0.0.0:6080 in your browser
      #        Important: http://127.0.0.1:6080 works but http://localhost:6080 doesn't
      - 6080:26080
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - NOVNC=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - SCREEN_WIDTH=1880
      - SCREEN_HEIGHT=1040
      - VIDEO=false
      - GRID=false
      - CHROME=true
      - FIREFOX=false
```

```rb
# spec/support/config/capybara.rb
require 'capybara'

app_host = ENV['APP_HOST']

if app_host.blank?
  puts 'Warning: No APP_HOST'
  puts 'Excluding feature tests'

  RSpec.configure do |config|
    config.filter_run_excluding type: :feature
  end
else
  Capybara.app_host = app_host
  Capybara.run_server = false

  hub_url = ENV['HUB_URL']
  raise 'Empty HUB_URL' unless hub_url

  caps = Selenium::WebDriver::Remote::Capabilities.chrome(
    'chromeOptions' => {
      'args' => [
        '--lang=en',
        '--no-default-browser-check',
        '--start-maximized',
        '--no-sandbox'
      ],
      'prefs' => {
        'download' => {
          'default_directory'   => ENV['REMOTE_DOWNLOAD_DIR'],
          'prompt_for_download' => false,
          'directory_upgrade'   => true,
          # 'extensions_to_open'  => ''
        },
        'plugins' => {
          'plugins_disabled' => ['Chrome PDF Viewer']
        }
      }
    }
  )

  Capybara.register_driver :chrome do |app|
    Capybara::Selenium::Driver.new(
      app,
      browser: :remote,
      url: hub_url,
      desired_capabilities: caps
    )
  end

  Capybara.default_driver = :chrome
  Capybara.javascript_driver = :chrome
end
```

#### Operating System
- [x] `Linux machine 4.9.63 #1-NixOS SMP Sat Nov 18 10:22:25 UTC 2017 x86_64 GNU/Linux`

#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

#### Docker version
- [x] I have latest version of docker and I will specify here the output of `docker --version`

Docker version 17.09.0-ce, build afdb6d44a80f777069885a9ee0e0f86cf841b1bb

#### Docker-Compose
_(if using docker-compose)_

- [x] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

docker-compose version 1.15.0, build e12f3b9
