### ISSUE TITLE
How to pass -enablePassThrough option to firefox

### ISSUE THREAD

**Issue by gerhat** [elgalu/docker-selenium#214]
Hello!

I am suddenly getting `Session [(null externalkey)]` error in firefox tests with codeception. 
Same issue as here: https://github.com/zalando/zalenium/issues/415

The workaround is supposed to be passing `-enablePassThrough false` in firefox, but I cannot get around it.

Can anybody inform me on how to pass this option?

Thanks in advance

**Comment by diemol** [comment]
HI @gerhat,

The images are using Selenium 3.9.0 and in this version Selenium disabled the flag. So 3.8.1 was the last version where this was supported. 

I read that this was done because people were not reporting bugs related to new versions of Firefox.

**Comment by gerhat** [comment]
Thanks for your answer @diemol 

Since it is a firefox binding issue (https://github.com/facebook/php-webdriver/issues/523) I managed to make it work using **3.8.1-p13** with the following setup:

 ```
  selenium:
      image: elgalu/selenium:3.8.1-p13
      container_name: php_selenium
      ports:
        - "4444:24444"
        - "5902:25900"
      volumes:
        - /dev/shm:/dev/shm
      privileged: true
      environment:
        - TZ="Europe/Athens"
        - SCREEN_WIDTH=1920
        - SCREEN_HEIGHT=1080
        - SELENIUM_HUB_PARAMS=-enablePassThrough false
        - SELENIUM_NODE_PARAMS=-enablePassThrough false
```

**Comment by diemol** [comment]
That's great!
Closing this issue then.

**Comment by mautz-et-tong** [comment]
I have found an issue in combination with zalenium and added a comment there:
zalando/zalenium#394
Maybe this is something for this issue.

**Comment by shivaoutdo** [comment]
hi gerghat, could you please provide the complete docker compose file

**Comment by bizmate** [comment]
I am still seeing the issue despite using `3.8.1` and passing by the HUB and NODE params

```
selenium:
  image: selenium/hub:3.8.1
  ports:
    - 4444
  environment:
    GRID_TIMEOUT: 300000
    SELENIUM_HUB_PARAMS: '-enablePassThrough false'
    SELENIUM_NODE_PARAMS: '-enablePassThrough false'
```
When i go on the hub page i see enablePassthrough still set to *true*
![SELENIUM-GRID_2019-12-04_03-44-47](https://user-images.githubusercontent.com/1427498/70110971-b9ddd200-1648-11ea-8837-2f593fb95fa2.png)

And on the selenium container i see 
```
seluser@f6ba23f0e080:/$ env | grep SEL
SELENIUM_NODE_PARAMS=-enablePassThrough false
SELENIUM_HUB_PARAMS=-enablePassThrough false
```
Anyone can help confirming if this is the right way of doing it?
