### ISSUE TITLE
Varying window sizes in CircleCI

### ISSUE THREAD

**Issue by tinganho** [elgalu/docker-selenium#228]
I noticed that the window size varies between `1040x855` and `1050x875` in CircleCI if I add the command:
```ts
chromeOptions.addArguments('--window-size=1024,860');
```

These are the docker configs:

```
image: elgalu/selenium
      shm_size: 1g
      privileged: true
      volumes:
        - /dev/shm:/dev/shm
      environment:
        SCREEN_WIDTH: 1280
        SCREEN_HEIGHT: 1000
      ports:
        - 4444:24444
        - 5901:25900
```

Here is a minimum reproducable project written in nodejs:
https://github.com/tinganho/selenium-circleci-bug

You can clone it and setup your CircleCi to follow the project. Try to rebuild a few times until you see, that the window size varies, like this:

<img width="477" alt="screen shot 2018-03-20 at 21 16 25" src="https://user-images.githubusercontent.com/1324476/37680422-233cacf4-2c84-11e8-9e9b-88e8d938961c.png">

The reproducable bug just opens a simple web page and checks it window size. It will redo the steps until it encounters the right window size `1040x855`.

Locally on my Mac, I always get the same size `1040x855`. This bug only seem to appear in CircleCi
